-- Optional activity journal for the Next.js/Supabase implementation.
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_email text,
  action text not null,
  entity_type text,
  entity_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.activity_logs enable row level security;

drop policy if exists "admins read activity logs" on public.activity_logs;

create policy "admins read activity logs" on public.activity_logs
  for select to authenticated
  using (public.is_kivuport_admin());

create or replace function public.log_kivuport_activity(
  activity_action text,
  activity_entity_type text default null,
  activity_entity_id bigint default null,
  activity_metadata jsonb default '{}'::jsonb
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.activity_logs(actor_email, action, entity_type, entity_id, metadata)
  values (auth.jwt() ->> 'email', activity_action, activity_entity_type, activity_entity_id, coalesce(activity_metadata, '{}'::jsonb));
$$;

revoke all on function public.log_kivuport_activity(text, text, bigint, jsonb) from public;
grant execute on function public.log_kivuport_activity(text, text, bigint, jsonb) to authenticated;