-- KivuPort advanced operations contracts.
-- Run after features.sql. External workers/providers consume the outbox tables.

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', false)
on conflict (id) do nothing;

drop policy if exists "users upload own avatar" on storage.objects;
drop policy if exists "users read own avatar" on storage.objects;
drop policy if exists "users delete own avatar" on storage.objects;
create policy "users upload own avatar" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users read own avatar" on storage.objects for select to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users delete own avatar" on storage.objects for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create table if not exists public.kivuport_team_roles (
  email text primary key,
  role text not null check (role in ('admin_principal', 'gestionnaire_reservations', 'comptable', 'agent_embarquement', 'gestionnaire_flotte')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.kivuport_role_permissions (
  role text not null,
  permission text not null,
  primary key (role, permission)
);

create table if not exists public.kivuport_email_outbox (
  id bigint generated by default as identity primary key,
  recipient_email text not null,
  subject text not null,
  html_content text not null,
  text_content text,
  kind text not null,
  dedupe_key text not null unique,
  status text not null default 'pending',
  attempts integer not null default 0,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.kivuport_guest_access (
  id bigint generated by default as identity primary key,
  reservation_id integer not null references public.reservations(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.kivuport_team_roles enable row level security;
alter table public.kivuport_role_permissions enable row level security;
alter table public.kivuport_email_outbox enable row level security;
alter table public.kivuport_guest_access enable row level security;

drop policy if exists "admins manage team roles" on public.kivuport_team_roles;
drop policy if exists "admins read permissions" on public.kivuport_role_permissions;
drop policy if exists "admins read legacy notification outbox" on public.kivuport_email_outbox;
drop policy if exists "admins read email outbox" on public.kivuport_email_outbox;
create policy "admins manage team roles" on public.kivuport_team_roles for all to authenticated using (public.is_kivuport_admin()) with check (public.is_kivuport_admin());
create policy "admins read permissions" on public.kivuport_role_permissions for select to authenticated using (public.is_kivuport_admin());
create policy "admins read email outbox" on public.kivuport_email_outbox for select to authenticated using (public.is_kivuport_admin());

insert into public.kivuport_role_permissions(role, permission) values
 ('admin_principal', 'reservations.manage'), ('admin_principal', 'payments.refund'), ('admin_principal', 'fleet.manage'), ('admin_principal', 'reports.read'), ('admin_principal', 'team.manage'),
 ('gestionnaire_reservations', 'reservations.manage'), ('comptable', 'payments.refund'), ('comptable', 'reports.read'), ('agent_embarquement', 'boarding.validate'), ('gestionnaire_flotte', 'fleet.manage')
on conflict do nothing;

create or replace function public.kivuport_has_permission(p_permission text)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_kivuport_admin() or exists (
    select 1 from public.kivuport_team_roles tr join public.kivuport_role_permissions rp on rp.role = tr.role
    where lower(tr.email) = lower(auth.jwt() ->> 'email') and tr.active and rp.permission = p_permission
  );
$$;

create or replace function public.enqueue_kivuport_email(
  p_recipient_email text,
  p_subject text,
  p_html_content text,
  p_text_content text,
  p_kind text,
  p_dedupe_key text
)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if auth.role() <> 'service_role' and not public.is_kivuport_admin() then raise exception 'Admin access required'; end if;
  insert into public.kivuport_email_outbox(recipient_email, subject, html_content, text_content, kind, dedupe_key)
  values (lower(trim(p_recipient_email)), p_subject, p_html_content, p_text_content, p_kind, p_dedupe_key)
  on conflict (dedupe_key) do update set recipient_email = excluded.recipient_email, subject = excluded.subject, html_content = excluded.html_content, text_content = excluded.text_content
  returning id into v_id;
  return v_id;
end;
$$;

create or replace view public.kivuport_revenue_report as
select date_trunc('day', p.date_paiement)::date as day, r.idvoyage as voyage_id, r.idpavillon as pavillon_id,
       count(*) as payments_count, sum(p.montant) as revenue
from public.paiements p join public.reservations r on r.id = p.idreservation
where p.statut::text = 'paye' group by 1, 2, 3;

create or replace function public.expire_kivuport_reservations(p_age interval default interval '30 minutes')
returns integer language plpgsql security definer set search_path = public as $$
declare v_count integer;
begin
  update public.reservations set statut = 'expiree', updated_at = now()
   where statut::text = 'en_attente' and created_at < now() - p_age;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.kivuport_has_permission(text) from public;
grant execute on function public.kivuport_has_permission(text) to authenticated;
revoke all on function public.enqueue_kivuport_email(text, text, text, text, text, text) from public;
grant execute on function public.enqueue_kivuport_email(text, text, text, text, text, text) to authenticated, service_role;
revoke all on function public.expire_kivuport_reservations(interval) from public;
grant execute on function public.expire_kivuport_reservations(interval) to service_role;
