-- KivuPort customer documents and operations.
-- Run after admin-policies.sql and operations.sql.
-- All application writes go through security-definer functions.

create extension if not exists pgcrypto;

create table if not exists public.kivuport_tickets (
  id bigint generated by default as identity primary key,
  reservation_id integer not null unique references public.reservations(id) on delete cascade,
  ticket_code text not null unique default ('TKT-' || upper(replace(gen_random_uuid()::text, '-', ''))),
  used_at timestamptz,
  used_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.kivuport_notifications (
  id bigint generated by default as identity primary key,
  recipient_email text not null,
  title text not null,
  message text not null,
  kind text not null default 'info',
  reservation_id integer references public.reservations(id) on delete cascade,
  read_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.kivuport_refunds (
  id bigint generated by default as identity primary key,
  payment_id integer not null references public.paiements(id) on delete cascade,
  amount numeric not null check (amount > 0),
  reason text not null,
  status text not null default 'requested',
  requested_by text not null,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.kivuport_incidents (
  id bigint generated by default as identity primary key,
  voyage_id integer not null references public.voyages(id) on delete cascade,
  title text not null,
  message text not null,
  new_departure timestamptz,
  status text not null default 'published',
  created_by text not null,
  created_at timestamptz not null default now()
);

alter table public.kivuport_tickets enable row level security;
alter table public.kivuport_notifications enable row level security;
alter table public.kivuport_refunds enable row level security;
alter table public.kivuport_incidents enable row level security;

drop policy if exists "clients read own tickets" on public.kivuport_tickets;
drop policy if exists "admins manage tickets" on public.kivuport_tickets;
drop policy if exists "clients read own notifications" on public.kivuport_notifications;
drop policy if exists "admins manage notifications" on public.kivuport_notifications;
drop policy if exists "admins manage refunds" on public.kivuport_refunds;
drop policy if exists "authenticated read incidents" on public.kivuport_incidents;
drop policy if exists "admins manage incidents" on public.kivuport_incidents;
create policy "clients read own tickets" on public.kivuport_tickets for select to authenticated using (reservation_id in (select r.id from public.reservations r join public.client c on c.id = r.idclient where lower(c.email) = lower(auth.jwt() ->> 'email')));
create policy "admins manage tickets" on public.kivuport_tickets for all to authenticated using (public.is_kivuport_admin()) with check (public.is_kivuport_admin());
create policy "clients read own notifications" on public.kivuport_notifications for select to authenticated using (lower(recipient_email) = lower(auth.jwt() ->> 'email'));
create policy "admins manage notifications" on public.kivuport_notifications for all to authenticated using (public.is_kivuport_admin()) with check (public.is_kivuport_admin());
create policy "admins manage refunds" on public.kivuport_refunds for all to authenticated using (public.is_kivuport_admin()) with check (public.is_kivuport_admin());
create policy "authenticated read incidents" on public.kivuport_incidents for select to authenticated using (true);
create policy "admins manage incidents" on public.kivuport_incidents for all to authenticated using (public.is_kivuport_admin()) with check (public.is_kivuport_admin());

create or replace function public.issue_kivuport_ticket(p_reservation_id integer)
returns public.kivuport_tickets
language plpgsql security definer set search_path = public
as $$
declare v_ticket public.kivuport_tickets;
begin
  if not public.is_kivuport_admin() and not exists (select 1 from public.reservations r join public.client c on c.id = r.idclient where r.id = p_reservation_id and lower(c.email) = lower(auth.jwt() ->> 'email')) then raise exception 'Reservation access denied'; end if;
  if not exists (select 1 from public.reservations where id = p_reservation_id and statut::text in ('arrive', 'embarque')) then raise exception 'Reservation is not paid'; end if;
  insert into public.kivuport_tickets(reservation_id) values (p_reservation_id) on conflict (reservation_id) do nothing;
  select * into v_ticket from public.kivuport_tickets where reservation_id = p_reservation_id;
  return v_ticket;
end;
$$;

create or replace function public.verify_kivuport_ticket(p_ticket_code text, p_voyage_id integer default null)
returns table(valid boolean, ticket_code text, reservation_id integer, message text)
language plpgsql security definer set search_path = public
as $$
declare v_ticket public.kivuport_tickets; v_reservation public.reservations;
begin
  if not public.is_kivuport_admin() then raise exception 'Admin access required'; end if;
  select * into v_ticket from public.kivuport_tickets where ticket_code = upper(trim(p_ticket_code)) for update;
  if not found then return query select false, upper(trim(p_ticket_code)), null::integer, 'Ticket introuvable'; return; end if;
  select * into v_reservation from public.reservations where id = v_ticket.reservation_id;
  if p_voyage_id is not null and v_reservation.idvoyage <> p_voyage_id then return query select false, v_ticket.ticket_code, v_ticket.reservation_id, 'Voyage incorrect'; return; end if;
  if v_ticket.used_at is not null then return query select false, v_ticket.ticket_code, v_ticket.reservation_id, 'Ticket deja utilise'; return; end if;
  if v_reservation.statut::text not in ('arrive', 'embarque') then return query select false, v_ticket.ticket_code, v_ticket.reservation_id, 'Paiement non confirme'; return; end if;
  update public.kivuport_tickets set used_at = now(), used_by = auth.jwt() ->> 'email' where id = v_ticket.id;
  update public.reservations set statut = 'embarque', updated_at = now() where id = v_reservation.id;
  return query select true, v_ticket.ticket_code, v_ticket.reservation_id, 'Embarquement valide';
end;
$$;

create or replace function public.request_kivuport_refund(p_payment_id integer, p_amount numeric, p_reason text)
returns public.kivuport_refunds
language plpgsql security definer set search_path = public
as $$
declare v_payment public.paiements; v_refund public.kivuport_refunds;
begin
  if not public.is_kivuport_admin() then raise exception 'Admin access required'; end if;
  select * into v_payment from public.paiements where id = p_payment_id for update;
  if not found or v_payment.statut::text <> 'paye' then raise exception 'Payment is not refundable'; end if;
  if p_amount <= 0 or p_amount > v_payment.montant then raise exception 'Invalid refund amount'; end if;
  insert into public.kivuport_refunds(payment_id, amount, reason, requested_by, status, processed_at)
  values (p_payment_id, p_amount, trim(p_reason), auth.jwt() ->> 'email', 'processed', now()) returning * into v_refund;
  update public.paiements set statut = 'rembourse', updated_at = now() where id = p_payment_id;
  perform public.transition_kivuport_reservation(v_payment.idreservation, 'rembourse', p_reason);
  return v_refund;
end;
$$;

create or replace function public.mark_kivuport_notification_read(p_notification_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.kivuport_notifications set read_at = now() where id = p_notification_id and lower(recipient_email) = lower(auth.jwt() ->> 'email');
end;
$$;

revoke all on function public.issue_kivuport_ticket(integer) from public;
grant execute on function public.issue_kivuport_ticket(integer) to authenticated;
revoke all on function public.verify_kivuport_ticket(text, integer) from public;
grant execute on function public.verify_kivuport_ticket(text, integer) to authenticated;
revoke all on function public.request_kivuport_refund(integer, numeric, text) from public;
grant execute on function public.request_kivuport_refund(integer, numeric, text) to authenticated;
revoke all on function public.mark_kivuport_notification_read(bigint) from public;
grant execute on function public.mark_kivuport_notification_read(bigint) to authenticated;
