-- KivuPort operational safeguards.
-- Run after admin-policies.sql in the Supabase SQL Editor.
-- This migration is intentionally re-runnable and uses the existing Supabase columns directly.

create table if not exists public.reservation_status_history (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_email text not null default coalesce(auth.jwt() ->> 'email', 'system'),
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  idpaiement integer not null unique references public.paiements(id) on delete cascade,
  external_reference text not null unique,
  provider text not null,
  provider_status text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reservation_status_history enable row level security;
alter table public.payment_transactions enable row level security;

drop policy if exists "admins read reservation status history" on public.reservation_status_history;
drop policy if exists "clients read own reservation status history" on public.reservation_status_history;
drop policy if exists "admins read payment transactions" on public.payment_transactions;
create policy "admins read reservation status history" on public.reservation_status_history for select to authenticated using (public.is_kivuport_admin());
create policy "clients read own reservation status history" on public.reservation_status_history for select to authenticated using (reservation_id in (select r.id from public.reservations r join public.client c on c.id = r.idclient where lower(c.email) = lower(auth.jwt() ->> 'email')));
create policy "admins read payment transactions" on public.payment_transactions for select to authenticated using (public.is_kivuport_admin());

create or replace function public.create_kivuport_reservation(
  p_date_reservation timestamptz,
  p_date_embarquement timestamptz,
  p_type_reservation text,
  p_poids_cargaison integer,
  p_idvoyage integer,
  p_idpavillon integer,
  p_prix_total numeric,
  p_client_nom text,
  p_client_prenom text,
  p_client_telephone text
)
returns table (id integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_client_id integer;
  v_boat_id integer;
  v_passenger_capacity integer;
  v_cargo_capacity integer;
  v_passenger_used integer;
  v_cargo_used integer;
  v_pavilion_boat integer;
  v_id integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_type_reservation not in ('passage', 'mixte', 'cargaison') then raise exception 'Invalid reservation type'; end if;
  if coalesce(p_prix_total, 0) < 0 or coalesce(p_poids_cargaison, 0) < 0 then raise exception 'Invalid reservation amount or cargo'; end if;

  select v.id, v.idbateau, b.capacite_passager, b.capacite_cargaison
    into v_id, v_boat_id, v_passenger_capacity, v_cargo_capacity
    from public.voyages v join public.bateaux b on b.id = v.idbateau
   where v.id = p_idvoyage and v.statut = 'prevu' for update;
  if v_id is null then raise exception 'Voyage unavailable'; end if;

  select p.idbateau into v_pavilion_boat from public.pavillons p where p.id = p_idpavillon;
  if v_pavilion_boat is null or v_pavilion_boat <> v_boat_id then raise exception 'Pavilion does not belong to voyage boat'; end if;

  select count(*) filter (where type_reservation <> 'cargaison'), coalesce(sum(poids_cargaison), 0)
    into v_passenger_used, v_cargo_used
    from public.reservations
   where idvoyage = p_idvoyage and statut in ('en_attente', 'confirme');
  if p_type_reservation <> 'cargaison' and v_passenger_used + 1 > v_passenger_capacity then raise exception 'Passenger capacity exceeded'; end if;
  if p_type_reservation <> 'passage' and v_cargo_used + coalesce(p_poids_cargaison, 0) > v_cargo_capacity then raise exception 'Cargo capacity exceeded'; end if;

  select c.id into v_client_id from public.client c where lower(c.email) = lower(auth.jwt() ->> 'email') limit 1;
  if v_client_id is null then
    insert into public.client(nom, prenom, email, telephone, date_inscription)
    values (trim(p_client_nom), trim(p_client_prenom), lower(trim(auth.jwt() ->> 'email')), trim(p_client_telephone), now())
    returning client.id into v_client_id;
  else
    update public.client set telephone = trim(p_client_telephone), updated_at = now() where public.client.id = v_client_id;
  end if;

  execute format('insert into public.reservations(date_reservation, date_embarquement, type_reservation, poids_cargaison, statut, idvoyage, idclient, idpavillon, prix_total) values ($1, $2, %L, $3, %L, $4, $5, $6, $7) returning id', p_type_reservation, 'en_attente')
    into v_id
    using coalesce(p_date_reservation, now()), p_date_embarquement, p_poids_cargaison, p_idvoyage, v_client_id, p_idpavillon, p_prix_total;
  insert into public.reservation_status_history(reservation_id, from_status, to_status, actor_email, reason)
  values (v_id, null, 'en_attente', auth.jwt() ->> 'email', 'reservation_created');
  return query select v_id;
end;
$$;

create or replace function public.transition_kivuport_reservation(
  p_reservation_id integer,
  p_to_status text,
  p_reason text default null
)
returns public.reservations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.reservations;
  v_from_status text;
  v_allowed boolean := false;
begin
  select * into v_reservation from public.reservations where id = p_reservation_id for update;
  if not found then raise exception 'Reservation not found'; end if;
  if auth.role() <> 'service_role' and not public.is_kivuport_admin() and not exists (select 1 from public.client where id = v_reservation.idclient and lower(email) = lower(auth.jwt() ->> 'email')) then raise exception 'Reservation access denied'; end if;
  v_from_status := v_reservation.statut::text;
  v_allowed := (v_from_status = 'en_attente' and p_to_status in ('confirme', 'annule', 'refusee', 'expiree'))
    or (v_from_status = 'confirme' and p_to_status in ('annule', 'arrive'))
    or (v_from_status = 'arrive' and p_to_status in ('embarque', 'termine', 'rembourse'))
    or (v_from_status = 'embarque' and p_to_status = 'termine');
  if not v_allowed then raise exception 'Transition % -> % is not allowed', v_reservation.statut, p_to_status; end if;
  execute format('update public.reservations set statut = %L, updated_at = now() where id = $1', p_to_status) using p_reservation_id;
  select * into v_reservation from public.reservations where id = p_reservation_id;
  insert into public.reservation_status_history(reservation_id, from_status, to_status, actor_email, reason)
  values (p_reservation_id, v_from_status, p_to_status, coalesce(auth.jwt() ->> 'email', 'system'), p_reason);
  return v_reservation;
end;
$$;

create or replace function public.create_kivuport_payment_intent(
  p_reservation_id integer,
  p_provider text default 'mobile_money'
)
returns table (payment_id integer, external_reference text, amount numeric, currency text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.reservations;
  v_payment_id integer;
  v_existing_reference text;
  v_reference text := 'KP-' || p_reservation_id || '-' || replace(gen_random_uuid()::text, '-', '');
begin
  select r.* into v_reservation from public.reservations r join public.client c on c.id = r.idclient
   where r.id = p_reservation_id and lower(c.email) = lower(auth.jwt() ->> 'email') for update;
  if not found then raise exception 'Reservation access denied'; end if;
  if v_reservation.statut::text <> 'confirme' then raise exception 'Reservation must be confirmed'; end if;
  select p.id, t.external_reference
    into v_payment_id, v_existing_reference
    from public.paiements p
    join public.payment_transactions t on t.idpaiement = p.id
   where p.idreservation = p_reservation_id and p.statut = 'en_attente'
   order by p.created_at desc
   limit 1
   for update;
  if v_payment_id is not null then
    return query select v_payment_id, v_existing_reference, v_reservation.prix_total, 'CDF'::text;
    return;
  end if;
  select p.id into v_payment_id
    from public.paiements p
   where p.idreservation = p_reservation_id and p.statut = 'en_attente'
   order by p.created_at desc
   limit 1
   for update;
  if v_payment_id is not null then
    insert into public.payment_transactions(idpaiement, external_reference, provider)
    values (v_payment_id, v_reference, p_provider)
    on conflict (idpaiement) do nothing;
    select external_reference into v_existing_reference from public.payment_transactions where idpaiement = v_payment_id;
    return query select v_payment_id, v_existing_reference, v_reservation.prix_total, 'CDF'::text;
    return;
  end if;
  if exists (select 1 from public.paiements where idreservation = p_reservation_id and statut = 'paye') then raise exception 'Payment already confirmed'; end if;
  insert into public.paiements(montant, devise, mode_paiement, date_paiement, statut, idreservation)
  values (v_reservation.prix_total, 'CDF', 'MOMO', now(), 'en_attente', p_reservation_id)
  returning id into v_payment_id;
  insert into public.payment_transactions(idpaiement, external_reference, provider)
  values (v_payment_id, v_reference, p_provider);
  return query select v_payment_id, v_reference, v_reservation.prix_total, 'CDF'::text;
end;
$$;

create or replace function public.create_kivuport_public_payment_link(p_reservation_id integer)
returns table (payment_id integer, external_reference text, amount numeric)
language plpgsql security definer
set search_path = public
as $$
declare
  v_reservation public.reservations;
  v_payment_id integer;
  v_reference text;
begin
  select * into v_reservation from public.reservations where id = p_reservation_id for update;
  if not found or v_reservation.statut::text <> 'confirme' then raise exception 'Reservation must be confirmed'; end if;
  select p.id, t.external_reference into v_payment_id, v_reference
    from public.paiements p join public.payment_transactions t on t.idpaiement = p.id
    where p.idreservation = p_reservation_id and p.statut = 'en_attente'
    order by p.created_at desc limit 1;
  if v_payment_id is null then
    v_reference := 'KP-' || p_reservation_id || '-' || replace(gen_random_uuid()::text, '-', '');
    insert into public.paiements(montant, devise, mode_paiement, date_paiement, statut, idreservation)
    values (v_reservation.prix_total, 'CDF', 'MOMO', now(), 'en_attente', p_reservation_id) returning id into v_payment_id;
    insert into public.payment_transactions(idpaiement, external_reference, provider)
    values (v_payment_id, v_reference, 'maisha_pay');
  end if;
  return query select v_payment_id, v_reference, v_reservation.prix_total;
end;
$$;

create or replace function public.process_kivuport_payment_webhook(
  p_external_reference text,
  p_provider_status text,
  p_amount numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns table (payment_id integer, reservation_id integer, result text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_transaction public.payment_transactions;
  v_payment public.paiements;
  v_result text;
begin
  select * into v_transaction from public.payment_transactions where external_reference = p_external_reference for update;
  if not found then raise exception 'Unknown payment reference'; end if;
  select * into v_payment from public.paiements where id = v_transaction.idpaiement for update;
  if v_payment.montant <> p_amount then raise exception 'Payment amount mismatch'; end if;
  if v_payment.statut::text = 'paye' and p_provider_status = 'succeeded' then
    return query select v_payment.id, v_payment.idreservation, 'already_processed'::text;
    return;
  end if;
  if v_payment.statut::text in ('paye', 'rembourse') then raise exception 'Payment is already final'; end if;

  v_result := case p_provider_status when 'succeeded' then 'paye' when 'refunded' then 'rembourse' when 'failed' then 'echoue' when 'cancelled' then 'echoue' else null end;
  if v_result is null then raise exception 'Unsupported provider status'; end if;
  execute format('update public.paiements set statut = %L, date_paiement = now(), updated_at = now() where id = $1', v_result) using v_payment.id;
  update public.payment_transactions set provider_status = p_provider_status, metadata = coalesce(p_metadata, '{}'::jsonb), updated_at = now() where id = v_transaction.id;
  if p_provider_status = 'succeeded' then
    perform public.transition_kivuport_reservation(v_payment.idreservation, 'arrive', 'payment_webhook');
  elsif p_provider_status = 'refunded' then
    perform public.transition_kivuport_reservation(v_payment.idreservation, 'rembourse', 'payment_webhook');
  end if;
  return query select v_payment.id, v_payment.idreservation, 'processed'::text;
end;
$$;

revoke all on function public.create_kivuport_reservation(timestamptz, timestamptz, text, integer, integer, integer, numeric, text, text, text) from public;
grant execute on function public.create_kivuport_reservation(timestamptz, timestamptz, text, integer, integer, integer, numeric, text, text, text) to authenticated;
revoke all on function public.transition_kivuport_reservation(integer, text, text) from public;
grant execute on function public.transition_kivuport_reservation(integer, text, text) to authenticated;
revoke all on function public.create_kivuport_payment_intent(integer, text) from public;
grant execute on function public.create_kivuport_payment_intent(integer, text) to authenticated;
grant execute on function public.create_kivuport_public_payment_link(integer) to service_role;
revoke all on function public.process_kivuport_payment_webhook(text, text, numeric, jsonb) from public;
grant execute on function public.process_kivuport_payment_webhook(text, text, numeric, jsonb) to service_role;

-- Direct writes are disabled: reservation and payment writes must use the RPCs.
drop policy if exists "client creates own reservations" on public.reservations;
drop policy if exists "client cancels own pending reservations" on public.reservations;
drop policy if exists "client creates own payments" on public.paiements;
